// Icons offered when choosing one for a weapon set. Every name here was
// checked against the Font Awesome 6.4 free stylesheet the app loads, so
// none of them can render as an empty square.
export const ICON_GROUPS: { group: string; icons: string[] }[] = [
  { group: 'Combate', icons: ["fa-bolt", "fa-bolt-lightning", "fa-bomb", "fa-bullseye", "fa-burst", "fa-crosshairs", "fa-dragon", "fa-explosion", "fa-fire", "fa-fire-flame-curved", "fa-fire-flame-simple", "fa-gavel", "fa-gun", "fa-hammer", "fa-hand-back-fist", "fa-hand-fist", "fa-jet-fighter", "fa-khanda", "fa-land-mine-on", "fa-meteor", "fa-person-rifle", "fa-skull", "fa-skull-crossbones", "fa-virus", "fa-wand-sparkles"] },
  { group: 'Defensa', icons: ["fa-archway", "fa-building-shield", "fa-dungeon", "fa-helmet-safety", "fa-house-lock", "fa-igloo", "fa-lock", "fa-lock-open", "fa-shield", "fa-shield-halved", "fa-shield-heart", "fa-shield-virus", "fa-torii-gate", "fa-tower-observation", "fa-umbrella-beach", "fa-vest", "fa-vest-patches", "fa-warehouse"] },
  { group: 'Soporte', icons: ["fa-bandage", "fa-briefcase-medical", "fa-flask", "fa-flask-vial", "fa-hand-holding-heart", "fa-hand-holding-medical", "fa-heart", "fa-heart-circle-plus", "fa-heart-pulse", "fa-kit-medical", "fa-mortar-pestle", "fa-notes-medical", "fa-prescription-bottle-medical", "fa-staff-snake", "fa-stethoscope", "fa-syringe", "fa-truck-medical", "fa-user-doctor", "fa-vial", "fa-vials"] },
  { group: 'Magia', icons: ["fa-atom", "fa-book", "fa-book-journal-whills", "fa-book-open", "fa-book-skull", "fa-brain", "fa-dice", "fa-dice-d20", "fa-dice-d6", "fa-eye", "fa-eye-low-vision", "fa-ghost", "fa-hand-sparkles", "fa-hat-wizard", "fa-hourglass", "fa-hourglass-end", "fa-hourglass-half", "fa-hourglass-start", "fa-infinity", "fa-scroll", "fa-spa", "fa-wand-magic", "fa-wand-magic-sparkles", "fa-yin-yang"] },
  { group: 'Elementos', icons: ["fa-cloud", "fa-cloud-bolt", "fa-cloud-showers-heavy", "fa-droplet", "fa-fire", "fa-icicles", "fa-leaf", "fa-moon", "fa-mountain", "fa-mountain-sun", "fa-seedling", "fa-smog", "fa-snowflake", "fa-star", "fa-sun", "fa-temperature-arrow-down", "fa-temperature-arrow-up", "fa-tornado", "fa-tree", "fa-volcano", "fa-water", "fa-wave-square", "fa-wind"] },
  { group: 'Criaturas', icons: ["fa-cat", "fa-crow", "fa-dog", "fa-dove", "fa-dragon", "fa-feather", "fa-feather-pointed", "fa-fish", "fa-fish-fins", "fa-frog", "fa-hippo", "fa-horse", "fa-horse-head", "fa-kiwi-bird", "fa-locust", "fa-mosquito", "fa-otter", "fa-paw", "fa-shrimp", "fa-spider", "fa-worm"] },
  { group: 'Movilidad', icons: ["fa-angles-right", "fa-arrow-trend-up", "fa-arrows-turn-right", "fa-backward-fast", "fa-bicycle", "fa-chevron-right", "fa-forward", "fa-forward-fast", "fa-gauge-high", "fa-person-hiking", "fa-person-running", "fa-person-walking", "fa-plane", "fa-road", "fa-rocket", "fa-shoe-prints", "fa-stairs", "fa-wind"] },
  { group: 'Rangos', icons: ["fa-award", "fa-certificate", "fa-chess-bishop", "fa-chess-king", "fa-chess-knight", "fa-chess-pawn", "fa-chess-queen", "fa-chess-rook", "fa-crown", "fa-flag", "fa-flag-checkered", "fa-gem", "fa-handshake", "fa-medal", "fa-people-group", "fa-ranking-star", "fa-star", "fa-trophy", "fa-user-astronaut", "fa-user-ninja", "fa-user-secret", "fa-user-shield", "fa-user-tie", "fa-users"] },
  { group: 'Objetos', icons: ["fa-anchor", "fa-archive", "fa-bell", "fa-box", "fa-bullhorn", "fa-calendar", "fa-campground", "fa-clock", "fa-coins", "fa-compass", "fa-drum", "fa-fan", "fa-fish-fins", "fa-gear", "fa-gears", "fa-gift", "fa-guitar", "fa-hat-cowboy", "fa-key", "fa-lightbulb", "fa-link", "fa-map", "fa-map-location-dot", "fa-music", "fa-sack-dollar", "fa-scissors", "fa-tent", "fa-toolbox", "fa-umbrella"] },
  { group: 'Formas', icons: ["fa-bezier-curve", "fa-certificate", "fa-circle", "fa-cube", "fa-cubes", "fa-diamond", "fa-draw-polygon", "fa-heart", "fa-layer-group", "fa-play", "fa-shapes", "fa-square", "fa-star", "fa-stop", "fa-vector-square"] },
];

export const ALL_ICONS = ICON_GROUPS.flatMap((g) => g.icons);
